# Beispiele zu Termin 3

## 1

Erstellen Sie zwei Vektoren $a$ und $b$, die die Zahlen ${0,2,4,6,8}$ enthalten, auf zwei Arten: einmal mit *arange* und einmal mit *linspace*. 

In [1]:
import numpy as np

In [14]:
a = np.arange(0,10,2)
b = np.linspace(0,8,5)
print('vector a = ', a)
print('vector b = ', b)

vector a =  [0 2 4 6 8]
vector b =  [0. 2. 4. 6. 8.]


Setzen Sie dann den ersten Eintrag in $b$ auf $1$ und geben Sie beide Vektoren aus. 

In [15]:
b[0] = 1
print('new vector b = ', b)

new vector b =  [1. 2. 4. 6. 8.]


Berechnen Sie nun das innere Produkt $⟨a,b⟩$ und $M=a∗b^{T}$ und geben Sie das Resultat und jeweils die resultierende Dimension aus (Achtung: zur Erstellung von M müssen Sie die Vektoren $a$ und $b$ als Matrizen auffassen, zB mit `np.asmatrix())`.  

In [16]:
i1 = a.dot(b)
i2 = np.dot(a,b)
i3 = a @ b
i1, i2, i3

(120.0, 120.0, 120.0)

In [17]:
i1 == i2 == i3

True

In [18]:
print('inner Produkt <a,b> = ', i1)

inner Produkt <a,b> =  120.0


In [71]:
a = np.asmatrix(a) # A = matrix a
b = np.asmatrix(b) # B = matrix b

print('Matrix a =', a)
print('Matrix b =', b)

Matrix a = [[0 2 4 6 8]]
Matrix b = [[1. 2. 4. 6. 8.]]


In [75]:
bt = np.transpose(b) #  == b.T
print('transpotiert b = \n'+ str(bt))

transpotiert b = 
[[1.]
 [2.]
 [4.]
 [6.]
 [8.]]


In [78]:
M = a * bt
M

matrix([[120.]])

In [52]:
# M = np.outer(A,bt)   # == M = A * Bt : 크로스곱. 외적
# print('Matrix M = \n'+str(M)) 

Matrix M = 
[[ 0.  0.  0.  0.  0.]
 [ 2.  4.  8. 12. 16.]
 [ 4.  8. 16. 24. 32.]
 [ 6. 12. 24. 36. 48.]
 [ 8. 16. 32. 48. 64.]]


In [ ]:
M = A *

In [44]:
dim_M = np.shape(M)
print('Dimension M =', dim_M)

Dimension M = (5, 5)


In [45]:
N = i1 # i1 = a.dot(b)
dim_N = np.shape(N)
print('Dimension <a,b> =', dim_N)

Dimension <a,b> = ()


Ersetzen Sie durch ausprobieren die Diagonale von $M$ nun so, dass das Gleichungssystem $Mx=b$ lösbar ist.

In [47]:
x = np.linalg.solve(M,b)
x #오류생김

LinAlgError: Singular matrix

In [64]:
from numpy.linalg import det   #이거 해야함

In [56]:
# M[np.diag_indices_from(M)] = 2
# np.linalg.det(M)

-499808.0

In [68]:
x = np.linalg.solve(M,b)
print(x)

[0.5        0.11809335 0.03374096 0.02084    0.01523785]


## 2-a)

Definieren Sie zunächst eine Funktion, die die Matrix 
$$ A_{x} = \begin{pmatrix} 1 - \cos x & \sin x \\ \sin x & 1 + \cos x \end{pmatrix}$$
für beliebige $x$ erstellt und zurückgibt. 

In [10]:
import numpy as np

In [11]:
def A_x(x):
    a1 = 1 - np.cos(x)
    a2 = np.sin(x)
    a3 = 1 + np.cos(x)
    
    A = np.array([[a1, a2],[a2,a3]])
    return A

In [12]:
A_x(0) #확인용

array([[0., 0.],
       [0., 2.]])

In [13]:
A_x(90)

array([[1.44807362, 0.89399666],
       [0.89399666, 0.55192638]])

In [14]:
A_x(np.pi/2)

array([[1., 1.],
       [1., 1.]])

Schreiben Sie eine weitere Funktion `potenzen`, die $A^{n}_{x}$ numerisch für beliebige $n$ berechnet, einmal mithilfe von `matrix_power(A,power)` aus dem Untermodul `linalg` und einmal durch wiederholtes Anwenden von `dot`. 
Die Funktion soll beide Matrizen zurückgeben. 

In [15]:
def potenzen(x,n):
    A = A_x(x)
    M1 = np.linalg.matrix_power(A,n)
    
    M2 = A.copy()
    for i in range(n-1):
        M2 = M2.dot(A)
    
    return M1, M2 

In [16]:
potenzen(0,3) #확인용 A_0^3

(array([[0., 0.],
        [0., 8.]]),
 array([[0., 0.],
        [0., 8.]]))

In [17]:
potenzen(6,1) #확인용 A_6^1

(array([[ 0.03982971, -0.2794155 ],
        [-0.2794155 ,  1.96017029]]),
 array([[ 0.03982971, -0.2794155 ],
        [-0.2794155 ,  1.96017029]]))

 Verwenden Sie nun den Befehl `np.finfo(np.float64).eps` um sich die *Maschinengenauigkeit* anzusehen mit welcher die Einträge abgespeichert sind.

In [18]:
np.finfo(np.float64).eps

2.220446049250313e-16

Vergleichen Sie dann für $x=6$ und $n=2,…,30$ auf wieviele Nachkommastellen die beiden Berechnungen gleich sind (vergleichen Sie hierfür bis zur *Maschinengenauigkeit*).

In [19]:
for i in np.arange(2,31):
    A_power, A_dot = potenzen(6,i)
    
    print('Matrix A_power with x = 6, n =', i, '\n', A_power)
    print('Matrix A_dot with x = 6, n =', i, '\n', A_dot, '\n-----------')

Matrix A_power with x = 6, n = 2 
 [[ 0.07965943 -0.558831  ]
 [-0.558831    3.92034057]]
Matrix A_dot with x = 6, n = 2 
 [[ 0.07965943 -0.558831  ]
 [-0.558831    3.92034057]] 
-----------
Matrix A_power with x = 6, n = 3 
 [[ 0.15931885 -1.11766199]
 [-1.11766199  7.84068115]]
Matrix A_dot with x = 6, n = 3 
 [[ 0.15931885 -1.11766199]
 [-1.11766199  7.84068115]] 
-----------
Matrix A_power with x = 6, n = 4 
 [[ 0.31863771 -2.23532399]
 [-2.23532399 15.68136229]]
Matrix A_dot with x = 6, n = 4 
 [[ 0.31863771 -2.23532399]
 [-2.23532399 15.68136229]] 
-----------
Matrix A_power with x = 6, n = 5 
 [[ 0.63727541 -4.47064797]
 [-4.47064797 31.36272459]]
Matrix A_dot with x = 6, n = 5 
 [[ 0.63727541 -4.47064797]
 [-4.47064797 31.36272459]] 
-----------
Matrix A_power with x = 6, n = 6 
 [[ 1.27455083 -8.94129594]
 [-8.94129594 62.72544917]]
Matrix A_dot with x = 6, n = 6 
 [[ 1.27455083 -8.94129594]
 [-8.94129594 62.72544917]] 
-----------
Matrix A_power with x = 6, n = 7 
 [[  2.5491

### 2-b)

Berechnen Sie $A^{n}_{6}$ für $n=1,…,4.$

In [20]:
for n in np.arange(1,5):
    A_power, A_dot = potenzen(6,n)
    
    print('Matrix A_power with x = 6, n =', n, '\n', A_power)
    print('Matrix A_dot with x = 6, n =', n, '\n', A_dot, '\n-----------')

Matrix A_power with x = 6, n = 1 
 [[ 0.03982971 -0.2794155 ]
 [-0.2794155   1.96017029]]
Matrix A_dot with x = 6, n = 1 
 [[ 0.03982971 -0.2794155 ]
 [-0.2794155   1.96017029]] 
-----------
Matrix A_power with x = 6, n = 2 
 [[ 0.07965943 -0.558831  ]
 [-0.558831    3.92034057]]
Matrix A_dot with x = 6, n = 2 
 [[ 0.07965943 -0.558831  ]
 [-0.558831    3.92034057]] 
-----------
Matrix A_power with x = 6, n = 3 
 [[ 0.15931885 -1.11766199]
 [-1.11766199  7.84068115]]
Matrix A_dot with x = 6, n = 3 
 [[ 0.15931885 -1.11766199]
 [-1.11766199  7.84068115]] 
-----------
Matrix A_power with x = 6, n = 4 
 [[ 0.31863771 -2.23532399]
 [-2.23532399 15.68136229]]
Matrix A_dot with x = 6, n = 4 
 [[ 0.31863771 -2.23532399]
 [-2.23532399 15.68136229]] 
-----------


Untersuchen sie nun genauso die Matrix $B_{x}= \frac{1}{2}A_{x}$, was fällt Ihnen dabei auf? 

In [22]:

def potenzen_B(x,n):
    B = 0.5 * A_x(x)
    M1 = np.linalg.matrix_power(B,n)
    
    M2 = B.copy()
    for i in range(n-1):
        M2 = M2.dot(B)
    
    return M1, M2 

In [23]:
for n in np.arange(1,5):
    B_power, B_dot = potenzen_B(6,n)
    
    print('Matrix B_power with x = 6, n =', n, '\n', B_power)
    print('Matrix B_dot with x = 6, n =', n, '\n', B_dot, '\n-----------')

Matrix B_power with x = 6, n = 1 
 [[ 0.01991486 -0.13970775]
 [-0.13970775  0.98008514]]
Matrix B_dot with x = 6, n = 1 
 [[ 0.01991486 -0.13970775]
 [-0.13970775  0.98008514]] 
-----------
Matrix B_power with x = 6, n = 2 
 [[ 0.01991486 -0.13970775]
 [-0.13970775  0.98008514]]
Matrix B_dot with x = 6, n = 2 
 [[ 0.01991486 -0.13970775]
 [-0.13970775  0.98008514]] 
-----------
Matrix B_power with x = 6, n = 3 
 [[ 0.01991486 -0.13970775]
 [-0.13970775  0.98008514]]
Matrix B_dot with x = 6, n = 3 
 [[ 0.01991486 -0.13970775]
 [-0.13970775  0.98008514]] 
-----------
Matrix B_power with x = 6, n = 4 
 [[ 0.01991486 -0.13970775]
 [-0.13970775  0.98008514]]
Matrix B_dot with x = 6, n = 4 
 [[ 0.01991486 -0.13970775]
 [-0.13970775  0.98008514]] 
-----------


Belegen Sie Ihre Vermutung indem Sie $B_{x}$ und $B^{2}_{x}$ für einige verschiedene {x} berechnen.

In [24]:
for x in np.arange(1,5):
    for n in np.arange(1,3):
        B_power, B_dot = potenzen_B(x,n)
        
        print('Matrix B_power with x = 6, n =', n, '\n', B_power)
        print('Matrix B_dot with x = 6, n =', n, '\n', B_dot, '\n-----------')

Matrix B_power with x = 6, n = 1 
 [[0.22984885 0.42073549]
 [0.42073549 0.77015115]]
Matrix B_dot with x = 6, n = 1 
 [[0.22984885 0.42073549]
 [0.42073549 0.77015115]] 
-----------
Matrix B_power with x = 6, n = 2 
 [[0.22984885 0.42073549]
 [0.42073549 0.77015115]]
Matrix B_dot with x = 6, n = 2 
 [[0.22984885 0.42073549]
 [0.42073549 0.77015115]] 
-----------
Matrix B_power with x = 6, n = 1 
 [[0.70807342 0.45464871]
 [0.45464871 0.29192658]]
Matrix B_dot with x = 6, n = 1 
 [[0.70807342 0.45464871]
 [0.45464871 0.29192658]] 
-----------
Matrix B_power with x = 6, n = 2 
 [[0.70807342 0.45464871]
 [0.45464871 0.29192658]]
Matrix B_dot with x = 6, n = 2 
 [[0.70807342 0.45464871]
 [0.45464871 0.29192658]] 
-----------
Matrix B_power with x = 6, n = 1 
 [[0.99499625 0.07056   ]
 [0.07056    0.00500375]]
Matrix B_dot with x = 6, n = 1 
 [[0.99499625 0.07056   ]
 [0.07056    0.00500375]] 
-----------
Matrix B_power with x = 6, n = 2 
 [[0.99499625 0.07056   ]
 [0.07056    0.00500375]]

### 2-c)

Die besondere Struktur von $B_{x}$ können wir zur Evaluation der Methoden `dot` und `np.matrix_power` verwenden.  
Rufen Sie Ihre Funktion `potenzen` für $B^{20}_{6}$ auf und 
vergleichen Sie die beiden Berechnungen mit $B$. 

In [25]:
B = 0.5 * A_x(x)

def potenzen_B(x,n):
    B = 0.5 * A_x(x)
    M1 = np.linalg.matrix_power(B,n)
    
    M2 = B.copy()
    for i in range(n-1):
        M2 = M2.dot(B)
    
    return M1, M2

In [26]:
B1, B2 = potenzen_B(6,1)
B3, B4 = potenzen_B(6,20)

print('Matrix B_power with x = 6, n = 1', '\n', B1)
print('Matrix B_dot with x = 6, n = 1', '\n', B2, 
      '\n--------------')

print('Matrix B_power with x = 6, n = 20', '\n', B3)
print('Matrix B_dot with x = 6, n = 20', '\n', B4, 
      '\n============================')

Matrix B_power with x = 6, n = 1 
 [[ 0.01991486 -0.13970775]
 [-0.13970775  0.98008514]]
Matrix B_dot with x = 6, n = 1 
 [[ 0.01991486 -0.13970775]
 [-0.13970775  0.98008514]] 
--------------
Matrix B_power with x = 6, n = 20 
 [[ 0.01991486 -0.13970775]
 [-0.13970775  0.98008514]]
Matrix B_dot with x = 6, n = 20 
 [[ 0.01991486 -0.13970775]
 [-0.13970775  0.98008514]] 


Wählen Sie dafür die Ausgabegenauigkeit hoch genug (zB mit `np.set_printoptions(precision=16)`).

In [27]:
np.set_printoptions(precision=16)

Wiederholen Sie dies für mehrere Werte $x$ und stellen Sie eine Vermutung auf, welche der beiden Methoden exakter rechnet.

In [28]:
for x in np.arange(2,7):
    B1, B2 = potenzen_B(x,1)
    B3, B4 = potenzen_B(x,2)
    np.set_printoptions(precision=16)

    print('Matrix B_power with x =', x, 'n = 1',
          '\n', B1)
    print('Matrix B_dot with x =', x, 'n = 1', 
          '\n', B2, 
          '\n--------------')

    print('Matrix B_power with x =', x, 'n = 20',
          '\n', B3)
    print('Matrix B_dot with x =', x, 'n = 20',
          '\n', B4, 
          '\n============================')

Matrix B_power with x = 2 n = 1 
 [[0.7080734182735712 0.4546487134128409]
 [0.4546487134128409 0.2919265817264288]]
Matrix B_dot with x = 2 n = 1 
 [[0.7080734182735712 0.4546487134128409]
 [0.4546487134128409 0.2919265817264288]] 
--------------
Matrix B_power with x = 2 n = 20 
 [[0.7080734182735712 0.4546487134128409]
 [0.4546487134128409 0.2919265817264288]]
Matrix B_dot with x = 2 n = 20 
 [[0.7080734182735712 0.4546487134128409]
 [0.4546487134128409 0.2919265817264288]] 
Matrix B_power with x = 3 n = 1 
 [[0.9949962483002227 0.0705600040299336]
 [0.0705600040299336 0.0050037516997773]]
Matrix B_dot with x = 3 n = 1 
 [[0.9949962483002227 0.0705600040299336]
 [0.0705600040299336 0.0050037516997773]] 
--------------
Matrix B_power with x = 3 n = 20 
 [[0.9949962483002226 0.0705600040299336]
 [0.0705600040299336 0.0050037516997773]]
Matrix B_dot with x = 3 n = 20 
 [[0.9949962483002226 0.0705600040299336]
 [0.0705600040299336 0.0050037516997773]] 
Matrix B_power with x = 4 n = 1 
 

Evaluieren Sie dies nun, indem Sie für $n=2,…,25$ folgendes für beide Methoden berechnen:
  $$ \sqrt{ \sum_{i=1}^2 \sum_{j=1}^2 (B_{ij} - B_{ij}^{n})^2  }.$$
Dies wird auch **Frobeniusnorm** genannt und kann mittels dem numpy Untermodul `linalg` und der Funktion `norm` berechnet werden. 
Wie verhalten sich die beiden Methoden?

In [136]:
# B1,B2 = potenzen_B(6,1)
# B3,b4 = potenzen_B(6,2)

# # B1,B2
# np.linalg.norm(B1 - B3)


2.7755575615628914e-17

In [29]:
import numpy as np

for n in np.arange(2,26):
    B1_pow, B1_dot = potenzen_B(6,1)
    Bn_pow, Bn_dot = potenzen_B(6,n)
    
    print(f'||B_6 - B_6^{n}pow|| = ', np.linalg.norm(B1_pow - Bn_pow))
    print(f'||B_6 - B_6^{n}dot|| = ', np.linalg.norm(B1_dot - Bn_dot),
          '\n-------')

||B_6 - B_6^2pow|| =  2.7755575615628914e-17
||B_6 - B_6^2dot|| =  2.7755575615628914e-17 
-------
||B_6 - B_6^3pow|| =  3.925231146709438e-17
||B_6 - B_6^3dot|| =  3.925231146709438e-17 
-------
||B_6 - B_6^4pow|| =  4.8074067159589095e-17
||B_6 - B_6^4dot|| =  6.369057972232327e-17 
-------
||B_6 - B_6^5pow|| =  6.369057972232327e-17
||B_6 - B_6^5dot|| =  9.159602786276758e-17 
-------
||B_6 - B_6^6pow|| =  6.947562107041945e-17
||B_6 - B_6^6dot|| =  1.1857187100668868e-16 
-------
||B_6 - B_6^7pow|| =  6.947562107041945e-17
||B_6 - B_6^7dot|| =  1.459231405488224e-16 
-------
||B_6 - B_6^8pow|| =  8.7289520232855e-17
||B_6 - B_6^8dot|| =  1.734723475976807e-16 
-------
||B_6 - B_6^9pow|| =  9.159602786276758e-17
||B_6 - B_6^9dot|| =  2.0113817612349073e-16 
-------
||B_6 - B_6^10pow|| =  9.570895620573757e-17
||B_6 - B_6^10dot|| =  2.2887833992611187e-16 
-------
||B_6 - B_6^11pow|| =  9.570895620573757e-17
||B_6 - B_6^11dot|| =  2.5666873818249836e-16 
-------
||B_6 - B_6^12pow|| =

### 2-d)

Mit den Untermodulen `Display` und `Latex` aus dem Modul `IPython.display` ist es möglich die Ausgaben mit *LaTex-Quellcode* zu formatieren. 
So können auch Laufvariablen integriert werden zB <br>
`for n in range(8,15):`<br>
`       display(Latex(f'$B^{ {n}}$:'),B)` <br>
Formatieren Sie dahingehend die Ausgabe Ihrer Lösungen in $a) - c)$ übersichtlich.


(**Zusatzaufgabe:** Vergleichen Sie was passiert, wenn in $A$ die Werte als `Decimal` anstatt `float` gespeichert werden.)

In [54]:
import numpy as np
from IPython.display import display, Latex
from decimal import Decimal

def A_x(x):
    a1 = 1 - np.cos(x)
    a2 = np.sin(x)
    a3 = 1 + np.cos(x)
    
    A = np.array([[a1, a2],[a2,a3]])
    return A

def potenzen(x,n):
    A = A_x(x)
    A_pow = np.linalg.matrix_power(A,n)
    
    A_dot = A.copy()
    for i in range(n-1):
        A_dot = A_dot.dot(A)
    
    return A_pow, A_dot


def potenzen_B(x,n):
    B = 0.5 * A_x(x)
    B_pow = np.linalg.matrix_power(B,n)
    
    B_dot = B.copy()
    for i in range(n-1):
        B_dot = B_dot.dot(B)
    
    return B_pow, B_dot

np.finfo(np.float64).eps
np.set_printoptions(precision=16)

A_pow, A_dot = potenzen(x,n)
B_pow, B_dot = potenzen_B(x,n)

In [72]:
import numpy as np
from IPython.display import display, Latex
from decimal import Decimal

def latex_A(x, n):
    display(Latex(
        r'''
        $A_{%s,power}^{%s} = 
        \begin{pmatrix} 
        {%s} & {%s} \\
        {%s} & {%s}
        \end{pmatrix}$
        
        $A_{%s,dot}^{%s} =
        \begin{pmatrix}
        {%s} & {%s} \\
        {%s} & {%s}
        \end{pmatrix}$
        '''
        % (x, n, A_pow[0,0], A_pow[0,1], A_pow[1,0], A_pow[1,1],
           x, n, A_dot[0,0], A_dot[0,1], A_dot[1,0], A_dot[1,1])
    ))
    
def latex_B(x, n):
    display(Latex(
        r'''
        $B_{%s,power}^{%s} = 
        \begin{pmatrix} 
        {%s} & {%s} \\
        {%s} & {%s}
        \end{pmatrix}$
        
        $B_{%s,dot}^{%s} =
        \begin{pmatrix}
        {%s} & {%s} \\
        {%s} & {%s}
        \end{pmatrix}$
        '''
        % (x, n, B_pow[0,0], B_pow[0,1], B_pow[1,0], B_pow[1,1],
           x, n, B_dot[0,0], B_dot[0,1], B_dot[1,0], B_dot[1,1])
    ))

#### 2-a)
 Definieren Sie zunächst eine Funktion, die die Matrix
$$ A_{x}= \begin{pmatrix}
1 − \cos x & \sin x \\
\sin x & 1 + \cos x
\end{pmatrix} $$

für beliebige $x$ erstellt und zurückgibt. 
Schreiben Sie eine weitere Funktion `potenzen`, die Anx numerisch für beliebige $n$ berechnet, 
einmal mithilfe von `matrix_power(A,power)` aus dem Untermodul `linalg` und einmal durch wiederholtes Anwenden von `dot`. 
Die Funktion soll beide Matrizen zurückgeben. 
Verwenden Sie nun den `Befehl np.finfo(np.float64).eps` um sich die *Maschinengenauigkeit* anzusehen mit welcher die Einträge abgespeichert sind.  
Vergleichen Sie dann für $x=6$ und $n=2,…,30$ auf wieviele Nachkommastellen die beiden Berechnungen gleich sind 
(vergleichen Sie hierfür bis zur *Maschinengenauigkeit*).  
Vergleichen Sie auch für weitere Werte von $x$.

In [66]:
A = A_x(6)

In [67]:
A

array([[ 0.039829713349634 , -0.2794154981989259],
       [-0.2794154981989259,  1.9601702866503659]])

In [69]:
for n in np.arange(2,31):
    A = A_x(6)
    A_pow, A_dot = potenzen(x,n)
    
    latex_A(6,n)

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

##### 같은 자리 소수점 구하기...

#### 2-b)
Berechnen Sie $A^{n}_{6}$ für $n=1,…,4.$ 
Untersuchen sie nun genauso die Matrix $B_{x}= \frac{1}{2} A_{x}$, was fällt Ihnen dabei auf? 
Belegen Sie Ihre Vermutung indem Sie $B_{x}$ und $B^{2}_{x}$ für einige verschiedene $x$ berechnen.

In [70]:
for n in np.arange(1,5):
    A = A_x(6)
    A_pow, A_dot = potenzen(x,n)
    
    latex_A(6,n)

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [73]:
for n in np.arange(1,5):
    B_pow, B_dot = potenzen_B(6,n)
    
    latex_B(6,n)

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [77]:
for x in np.arange(1,7):
    for n in np.arange(1,3):
        B_pow, B_dot = potenzen_B(x,n)
        
        latex_B(x,n)

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

#### 2-c)

Die besondere Struktur von $B_{x}$ können wir zur Evaluation der Methoden `dot` und `np.matrix_power` verwenden. <br>
Rufen Sie Ihre Funktion `potenzen` für $B^{20}_{6}$ auf und 
vergleichen Sie die beiden Berechnungen mit $B$. <br>
Wählen Sie dafür die Ausgabegenauigkeit hoch genug (zB mit `np.set_printoptions(precision=16)`). <br>
Wiederholen Sie dies für mehrere Werte $x$ und stellen Sie eine Vermutung auf, welche der beiden Methoden exakter rechnet. <br>
Evaluieren Sie dies nun, indem Sie für $n=2,…,25$ folgendes für beide Methoden berechnen:
  $$ \sqrt{ \sum_{i=1}^2 \sum_{j=1}^2 (B_{ij} - B_{ij}^{n})^2  }.$$ 
Dies wird auch **Frobeniusnorm** genannt und kann mittels dem numpy Untermodul `linalg` und der Funktion `norm` berechnet werden. <br>
Wie verhalten sich die beiden Methoden?


In [78]:
A = A_x(6)
B1, B2 = potenzen_B(6,1)
B3, B4 = potenzen_B(6,20)

latex_B(6,1)
latex_B(6,20)

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [84]:
for x in np.arange(1,7):
    A = A_x(x)
    B = 0.5 * A
    B_pow, B_dot = potenzen_B(x,20)
    
    latex_B(x,20)

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [88]:
## 계산 다시해라잉~~~

for n in np.arange(2,26):
    A = A_x(6)
    B = 0.5 * A
    
    B1_pow, B1_dot = potenzen_B(6,1)
    Bn_pow, Bn_dot = potenzen_B(6,n)
    
    display(Latex(r'''
    $||B_{6} - B_{6,power}^{%s}||$ = ${%s}$''' 
                  % (n, np.linalg.norm(B1_pow - Bn_pow),) 
                 ))
    
    display(Latex(r'''
    $||B_{6} - B_{6,dot}^{%s}||$ = ${%s}$''' 
                  % (n, np.linalg.norm(B1_dot - Bn_dot)) 
                 ))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>