# 2. Gleichungssystem

Lösen Sie das folgende Gleichungssystem einmal ausschließlich mit `sympy` Routinen und einmal mit `numpy`:
$$5x+4y+3z = 2,$$
$$2x+3y+z = 0,$$
$$3x+3y+z = 2$$
Geben Sie die Ergebnisse für $x, y, z$ sinnvoll strukturiert am Bildschirm aus.


## Practice

### mit `sympy`

In [1]:
from sympy import *

In [4]:
x, y, z = symbols('x y z')

In [3]:
f = 5*x + 4*y + 3*z - 2
g = 2*x + 3*y + z
h = 3*x + 3*y + z - 2

In [6]:
f

5*x + 4*y + 3*z - 2

In [7]:
g

2*x + 3*y + z

In [10]:
h

3*x + 3*y + z - 2

In [11]:
s = solve([f,g,h],[x,y,z])
s

{x: 2, y: -4/5, z: -8/5}

In [12]:
s[y]

-4/5

In [13]:
float(s[y])

-0.8

In [14]:
for i,j in zip('xyz',s):
    print(f'{i} = {float(s[j])}')

x = 2.0
y = -0.8
z = -1.6


[zip 1](https://ooyoung.tistory.com/60) <br>
[zip 2](https://chancoding.tistory.com/144)

### mit `numpy`

[넘파이 연립방정식1](https://rich-developer.tistory.com/112) <br>
[넘파이 연립방정식2](https://silver-liq9118.tistory.com/entry/Numpy-%EC%97%B0%EB%A6%BD%EB%B0%A9%EC%A0%95%EC%8B%9D)

In [15]:
import numpy as np

In [16]:
A = np.array([ [5,4,3],[2,3,1],[3,3,1] ] )
A

array([[5, 4, 3],
       [2, 3, 1],
       [3, 3, 1]])

In [17]:
b = np.array([2,0,2])
b

array([2, 0, 2])

In [19]:
k = np.linalg.solve(A,b)
k

array([ 2. , -0.8, -1.6])

In [20]:
for i,j in zip('xyz',k):
    print(f'{i} = {round(j,1)}')

x = 2.0
y = -0.8
z = -1.6


[소수점반올림,올림,내림](https://dpdpwl.tistory.com/94) <br>
[round](https://wikidocs.net/21113)

***

## Answers

In [21]:
# sympy

from sympy import *

x, y, z =symbols('x y z')

f = 5*x + 4*y + 3*z - 2
g = 2*x + 3*y + z
h = 3*x + 3*y + z - 2

s = solve([f,g,h],[x,y,z])

for i,j in zip('xyz',s):
    print(f'{i} = {float(s[j])}')

x = 2.0
y = -0.8
z = -1.6


In [22]:
# numpy

import numpy as np

A = np.array([ [5,4,3],[2,3,1],[3,3,1] ] )
b = np.array([2,0,2])
k = np.linalg.solve(A,b)

for i,j in zip('xyz',k):
    print(f'{i} = {round(j,1)}')

x = 2.0
y = -0.8
z = -1.6
